### ISSUE TITLE
Erreur Tuto Fonction inexistante

### ISSUE THREAD

**Issue by Zolac-dev** [CeriAvignon/GraphCentrality#10]
Erreur dans le tuto page 8/9 la fonction linkNode() est inexistante . Je crois qu'elle a été remplacé par createLink()

**Comment by JackassDestroyer** [comment]
C'est cela, la fonction en question a été remplacé par son nouveau nom

**Comment by vlabatut** [comment]
@Zolac-san pareil que pour l'autre issue : vérifie et ferme si c'est ok.
