### ISSUE TITLE
[g10] pour [g07] problème entre tutoriel et code

### ISSUE THREAD

**Issue by ChristopheManrique** [CeriAvignon/GraphCentrality#14]
Bonjour, 

Je pense avoir repéré une erreur dans le tutoriel / dans le code concernant le nom de 2 interfaces pour les types de graphes par rapport aux noms des interfaces dans le code.

Dans la section 2 vous présentez plusieurs interfaces auxquelles il faut ajouter le suffixe Centrality pour les utiliser dans nos mesures.

Hors si on suit votre tutoriel votre interface s'appelle WeightedSpatialGraph (dans le tuto) donc en toute logique elle devrait se transformer en WeightedSpatialCentrality dans nos mesures si j'ai bien compris.
Sauf que dans votre code elle a été nommé SpatialWeightedCentrality . 
Pareil pour celle avec le préfixe Directed

Je pense que l'erreur est du coté du code à mon avis.

Christophe

**Comment by JackassDestroyer** [comment]
Nous avons décider de ne pas toucher au code (du moins le moins possible, pour ce qui est de la structure de base), vu qu'il ne reste que deux semaines de cours. Nous avons donc simplement renommé les noms sur le tutoriel pour éviter toute confusion.
Je tiens à préciser qu'une modification a été faite sur le tutoriel concernant l'utilisation multiple de centralité au sein d'une même classe; ceci est devenu impossible depuis l'ajout de la classe AbstractCentrality. Je posterai un message sur le forum pour prévenir tout le monde.
