### ISSUE TITLE
Affectation incorrect du poids des liens

### ISSUE THREAD

**Issue by ChristopheManrique** [CeriAvignon/GraphCentrality#15]
Bonjour, 

Dans un graphe spatial simple et pondéré le poids des arcs est incorrects.
Exemple : 
Je crée 2 noeuds a et b, puis un arc avec un poids x entre a et b, l'arc entre a et b a le poids voulu mais l'arc entre b et a,  a systématiquement 1 comme poids.

Exemple de code qui ne fonctionne pas
`
SpatialWeightedGraph graphRapport = new SpatialWeightedGraph();
		
// creation de 2 noeuds
SpatialNode[] nodes = new SpatialNode[2];
nodes[0] = graphRapport.createNode(-3, 3); // v1
nodes[1] = graphRapport.createNode(0, 4);  // v2 

// creation de 1 lien
graphRapport.createLink(nodes[0], nodes[1], Math.sqrt(10));

List<WeightedLink> linkNode0 = graphRapport.getNodeLinks(nodes[0]);
List<WeightedLink> linkNode1 = graphRapport.getNodeLinks(nodes[1]);

WeightedLink currentLink = null ;
for	(int i=0 ; i < linkNode0.size() ; i++) {
	currentLink = linkNode0.get(i);
	System.out.println("source : " + currentLink.getSourceIdentifier() + "; dest : " + currentLink.getDestinationIdentifier() + " ; weight : " + currentLink.getWeight());
}
		
System.out.println("link of node id : " + nodes[1].getIdentifier());
currentLink = null ;
for	(int i=0 ; i < linkNode1.size() ; i++) {
	      currentLink = linkNode1.get(i);
	      System.out.println("source : " + currentLink.getSourceIdentifier() + "; dest : " + currentLink.getDestinationIdentifier() + " ; weight : " + currentLink.getWeight());
}
`

Après avoir debuguer avec des breakpoints il semble que le problème vienne de la méthode createLink.
2 captures pour expliciter l'une la sortie après execution, l'autre les valeurs des variables pendant le debug juste après l'execution de la méthode createLink 

![edgebug](https://user-images.githubusercontent.com/31924363/39868037-27736b36-5458-11e8-8aa6-b08290f62965.PNG)
![edgebug2](https://user-images.githubusercontent.com/31924363/39868038-278c48d6-5458-11e8-809c-7ad39848ea5b.PNG)

**Comment by JackassDestroyer** [comment]
Merci pour ta précision, nous avons réglé le bug (tu peux regarder les commits si tu veux plus de détail)
