### ISSUE TITLE
Probleme interface

### ISSUE THREAD

**Issue by Zolac-dev** [CeriAvignon/GraphCentrality#17]
Vous avez update la façon dont procèdent les interfaces de centralité. Maintenant celle-ci hérite tous AbstractCentrality.  Or cela pose problème aux groupes qui ont besoin d’implémenter 2 interfaces car leur centralité fonctionne sur 2 types de graphes différents (par exemple directed et simple).
Y aurait-il une solution?

**Comment by JackassDestroyer** [comment]
Alors la solution immédiate est de simplement créer une classe pour chaque types de graphes. Nous pouvons toujours revenir sur la version précédente, mais cela peut poser problème pour les groupes ayant déjà entamé leurs mesures, nous ne changerons donc pas le code (vu qu'il reste que deux semaines).
