### ISSUE TITLE
Problème de récupération des poids des liens quand on lit un fichier de graph à l'intermédiaire de GraphMLReader

### ISSUE THREAD

**Issue by arinik9** [CeriAvignon/GraphCentrality#5]
Hi @JackassDestroyer , je n'arrive pas à récupérer les poids des liens quand on lit un fichier de graphe à l'intermédiaire de GraphMLReader même si j'utilise la classe "WeightedGraph" pour mon objet de graph. Je n'ai que des valeurs 0 comme si le graph n'avait pas de poids. Est-ce je rate un truc ou il y a un bug? Peut-être le même problème existe pour les graphs de format "Gexf", mais je ne l'ai pas vérifié.  Pourrais-tu me répondre à propos de ce sujet STP? Je transmets le fichier de graphe que j'ai utilisé en pièce jointe et je partage mon code ci-dessous:

[g-wfloat-und.graphml.zip](https://github.com/CeriAvignon/GraphCentrality/files/1499826/g-wfloat-und.graphml.zip)

```java
WeightedGraph graph = new WeightedGraph();
GraphMLReader reader = new GraphMLReader();
reader.updateFromFile("PATH TO FILE", graph);

Vector<WeightedLink> links = graph.getLinks();
Iterator itr = links.iterator();
while(itr.hasNext()) {
	WeightedLink link = (WeightedLink) itr.next();
	System.out.println( "weight: " + link.getWeight() );
}
```

**Comment by JackassDestroyer** [comment]
Je viens de submit un hotfix pour votre problème, tout devrait être bon.
J'ai pas encore faire de submit sur la branch master, 'gettez' sur la branch g07 pour vérifier

**Comment by arinik9** [comment]
Oui c'est bon, merci! Par contre, il y avait un bug dans le fichier "OrientedAlgorithm.java": J'ai remplacé la ligne "inGraph.at(i)" par "inGraph.getNodeAt(i)" ==> la ligne 22
