### ISSUE TITLE
IDs redondants dans la liste d'adjacence pour des graphes de types "weighted" et "simple"

### ISSUE THREAD

**Issue by arinik9** [CeriAvignon/GraphCentrality#6]
Salut @JackassDestroyer , Je signale un autre bug:
Quand on crée une liste d'adjacence à partir d'un graphe de type "weighted" et "simple", on voit des IDs redondants. J'ai vérifié que vous avez aussi utilisé la même méthode qui est "linkNode()" dans le tutoriel (je me demandais s'il fallait utiliser une autre).

[bug](https://user-images.githubusercontent.com/4349076/33204090-9dddae00-d102-11e7-8ad9-898557b5c061.png)

 Pour les graphes orientés, c'est bon, pas de problème.
Je mets mon capture d'écran pour le résultat et partage mon code (pour un graph pondéré) ci-dessous:

```java
WeightedGraph graph = new WeightedGraph();
Node node0 = graph.createNode();
Node node1 = graph.createNode();
Node node2 = graph.createNode();
Node node3 = graph.createNode(); // isolated node
graph.linkNode(node0, node1);
graph.linkNode(node0, node2);
graph.linkNode(node1, node2);
graph.linkNode(node2, node0);
		
		
AdjacencyList adjList = new AdjacencyList();
adjList.copyGraph(graph);
adjList.print();
```

Une autre remarque, je pense que ce serait plus lisible si on voit l'ID du noeud de source dans l'affichage (avec print() ) au lieu d'un truc comme "fr.univavignon.graphcentr.g07.core.Node@6bc7c054". Tu vas comprendre mieux quand tu regardes la capture d'écran

**Comment by vlabatut** [comment]
Pour la dernière remarque de Nejat : il faut simplement surcharger `toString()` dans la classe concernée.

**Comment by JackassDestroyer** [comment]
Je viens de submit un fix pour ce bug.
Concernant l'affichage du noeud source, je peux effectivement override la method toString(), mais il faut fixer une façon d'afficher les noeuds du style : 
ID_Noeud, Weight, Location.
Qu'en pensez-vous ?

**Comment by arinik9** [comment]
J'ai eu l'occasion de parler avec Vincent sur ce sujet. Il pense qu'on n'a pas vraiment besoin de stocker toutes les informations dans la liste d'adjacence (pour ce projet). En fait, ca dépend des besoins des groupes qui sont en charge des mesures de centralité. Ils ne vont pas probablement utiliser l'information de "location". La question qui se pose est plûtot pour le poids. Peut-etre ce serait mieux d'attendre la séance prochaine pour la conception/l'affichage définitive
