### ISSUE TITLE
Erreur Tuto Package

### ISSUE THREAD

**Issue by Zolac-dev** [CeriAvignon/GraphCentrality#9]
J'ai trouvé une petite erreur dans le pdf du tutoriel. Les package inséré dans les exemples sont incorrect. C'est pas un gros problème mais quand on débute avec votre structure le mieux est de copier-coller vos exemples. Cela a donc posé un petit problème.

**Comment by vlabatut** [comment]
Oui, il faut corriger ça au plus vite. Il s'agit bien du tutoriel disponible sur e-uapv ?

**Comment by Zolac-dev** [comment]
l'erreur se trouve dans le tuto github et e-uapv

**Comment by Zolac-dev** [comment]
En allant vérfier, j'ai remarqué un autre erreur dans le tuto. Page 8/9 vous appelez une fonction : linkNode() d'après la nouvelle structure la fonction est createLink().

**Comment by vlabatut** [comment]
Il faut ouvrir une autre issue, comme c'est une erreur différente (on ne sait pas à l'avance combien il va y en avoir au final). Il faut du coup être plus précis dans le titre de cette issue, et de la nouvelle que tu va créer.

**Comment by JackassDestroyer** [comment]
C'est bon, les packages ont été corrigés

**Comment by vlabatut** [comment]
@Zolac-san , tu fermes l'issue après vérification de la correction.
